### PR TITLE
Feat/kap 202 rework program list

### PR DESCRIPTION
**Pull request by eriktmidtun**
I have tried to rework the show list cards. I'm looking for feedback on the the different screen sizes and to see if this is a better way to display the shows across different devices.
I know there is some problems with the title sizes, will try to fix this later.

Screen size bigger than 1000px - Desktop
shows- big

Screen size bigger than 800px - Desktop 0.5*screen
shows- medium

Screen size bigger than 550px - iPad
shows- small

Screen size smaller than 550px - Phones
shows- small

### CODE REVIEW

**Comment by santi** [comment]
Big disclaimer: I'm not a designer. 😱 

I think the layout for > 800px and > 1000px looks nice.

The > 550px and < 550px screens look a little "empty". Maybe it is possible to include the description here as well, but align it to the left side along with the title? Also, the tags on the images are quite big compared to the smaller images, so maybe they can be made smaller aswell?

**Comment by tobinus** [comment]
I really like the changes for smaller devices. I have always found it bothersome to scroll on mobile due to the massive space use.

Just chiming in to point out that text should be left-justified, with only a couple exceptions. It has to do with making it easy to read; it is very tiresome to read text where you need to work to find the beginning of the line. It is much easier to read when the beginning of the line is in a consistent place :)

In this case, I think the descriptions should be left-justified since they're rather long. The show titles _may_ be centered when there is a description to make them stand out, but when the titles are shown alone I think they'd better be left-justified, to support scanning for a specific show.

Some details on left-justified text: https://www.nngroup.com/articles/right-justified-navigation-menus/

(som inaktiv pang prøver jeg å ikke blande meg inn i ting, men tenker dette kan være kjekt å vite om :) )

**Comment by eriktmidtun** [comment]
** UPDATE **

I have left the bigger versions as is with the exception of left-justifying the description. Just like @tobinus proposed.
image
image

I tried to make different ways of displaying the category tags, but it ultimately came down to replacing the tag with just a left sided border with the same color as the tag. I think the problem of loosing the information of what the category is what color will get less of a problem when we eventually implement a search bar, and maybe make it sticky.

Left-justifying the text and increasing the font-size made the cards look less empty and easier to read. Do you agree @santi ?

< 800px iPad
image

< 550px Phones
image

The code needs a little cleanup before a merge.

**Comment by santi** [comment]
Looks great! 💯 

Only problem I see with the colors on the left border is that it is technically possible to put a show in multiple categories. How should we handle that?

**Comment by santi** [comment]
It might lead to a lot of hacky code, but what about the possibility of dividing the left bar into parts with different color? So that if a program belongs to two categories, the upper half is one color and the bottom half is another color?

**Comment by eriktmidtun** [comment]
> It might lead to a lot of hacky code, but what about the possibility of dividing the left bar into parts with different color? So that if a program belongs to two categories, the upper half is one color and the bottom half is another color?
I'm not sure if a rainbow would look good and it might lead to confusion for the users, but i can try to make a mockup.
We can always ask the question if there should be possible to have more than one category. Not sure how it would look on the bigger screens either, since one of the tags are quite long and could potentially take more space than it should.

**Comment by santi** [comment]
Agreed. We currently have no shows with more than one category, so it should be possible to make it into a field with a single value, not a list.

**Pull request merged**
